/* 
 * AUTOMATICALLY GENERATED FILE
 * Source: royalchallengers.com + iplt20.com (verified)
 * Season: IPL 2026
 * Sync Triggered: 2026-04-04T22:08:42.395Z
 * 
 * WARNING: DO NOT EDIT THIS FILE MANUALLY. 
 * This file is synced every 30 minutes via GitHub Actions.
 * All scorecard data is verified from official sources — NO hallucinated stats.
 */

window.ALL_IPL_2026 = [
  {
    "id": 1,
    "date": "2026-03-28",
    "time": "19:30",
    "t1": "RCB",
    "t2": "SRH",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "t1runs": "203/4",
    "t1ovs": "15.4",
    "t2runs": "201/9",
    "t2ovs": "20",
    "result": "RCB won by 6 wickets",
    "winner": "RCB",
    "rcb": true,
    "potm": "Jacob Duffy",
    "scorecard": {
      "toss": "SRH won the toss and elected to bat",
      "inn1": {
        "team": "SRH",
        "score": "201/9 (20 Ov)",
        "bat": [
          [
            "Ishan Kishan (c)",
            "c Salt b Duffy",
            80,
            38,
            8,
            5,
            "210.53"
          ],
          [
            "Aniket Verma",
            "c Patidar b Shepherd",
            43,
            18,
            3,
            4,
            "238.89"
          ],
          [
            "Heinrich Klaasen",
            "c Salt b Abhinandan",
            31,
            22,
            2,
            2,
            "140.91"
          ],
          [
            "Nitish Kumar Reddy",
            "b Shepherd",
            18,
            14,
            1,
            1,
            "128.57"
          ],
          [
            "Pat Cummins",
            "c Padikkal b Suyash",
            10,
            8,
            1,
            0,
            "125.00"
          ],
          [
            "Shahbaz Ahmed",
            "run out (Kohli)",
            7,
            5,
            1,
            0,
            "140.00"
          ],
          [
            "Harsh Dubey",
            "c Kohli b Krunal",
            4,
            3,
            0,
            0,
            "133.33"
          ],
          [
            "Zeeshan Ansari",
            "b Shepherd",
            2,
            2,
            0,
            0,
            "100.00"
          ],
          [
            "David Payne",
            "not out",
            0,
            1,
            0,
            0,
            "0.00"
          ],
          [
            "Extras",
            "(b 2, lb 3, w 3)",
            " ",
            " ",
            " ",
            " ",
            "8"
          ]
        ],
        "bowl": [
          [
            "Jacob Duffy",
            "4",
            "0",
            "22",
            "3",
            "5.50"
          ],
          [
            "Bhuvneshwar Kumar",
            "4",
            "0",
            "31",
            "1",
            "7.75"
          ],
          [
            "Romario Shepherd",
            "4",
            "0",
            "54",
            "3",
            "13.50"
          ],
          [
            "Abhinandan Singh",
            "3",
            "0",
            "38",
            "1",
            "12.67"
          ],
          [
            "Suyash Sharma",
            "3",
            "0",
            "28",
            "1",
            "9.33"
          ],
          [
            "Krunal Pandya",
            "2",
            "0",
            "26",
            "0",
            "13.00"
          ]
        ]
      },
      "inn2": {
        "team": "RCB",
        "score": "203/4 (15.4 Ov)",
        "bat": [
          [
            "Virat Kohli",
            "not out",
            69,
            38,
            5,
            4,
            "181.58"
          ],
          [
            "Devdutt Padikkal",
            "c Klaasen b Cummins",
            61,
            26,
            5,
            5,
            "234.62"
          ],
          [
            "Rajat Patidar (c)",
            "c Kishan b Payne",
            31,
            12,
            2,
            3,
            "258.33"
          ],
          [
            "Phil Salt (wk)",
            "b Unadkat",
            24,
            16,
            2,
            2,
            "150.00"
          ],
          [
            "Romario Shepherd",
            "not out",
            11,
            5,
            1,
            1,
            "220.00"
          ],
          [
            "Extras",
            "(lb 1, w 6)",
            " ",
            " ",
            " ",
            " ",
            "7"
          ]
        ],
        "bowl": [
          [
            "David Payne",
            "4",
            "0",
            "35",
            "2",
            "8.75"
          ],
          [
            "Jaydev Unadkat",
            "3",
            "0",
            "29",
            "1",
            "9.67"
          ],
          [
            "Harsh Dubey",
            "3",
            "0",
            "35",
            "1",
            "11.67"
          ],
          [
            "Pat Cummins",
            "3",
            "0",
            "51",
            "1",
            "17.00"
          ],
          [
            "Shahbaz Ahmed",
            "2.4",
            "0",
            "46",
            "0",
            "17.25"
          ]
        ]
      }
    }
  },
  {
    "id": 2,
    "date": "2026-03-29",
    "time": "19:30",
    "t1": "MI",
    "t2": "KKR",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "t1runs": "182/5",
    "t1ovs": "20",
    "t2runs": "183/3",
    "t2ovs": "17.3",
    "result": "KKR won by 7 wickets",
    "winner": "KKR",
    "rcb": false
  },
  {
    "id": 3,
    "date": "2026-03-30",
    "time": "19:30",
    "t1": "CSK",
    "t2": "RR",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "t1runs": "196/5",
    "t1ovs": "20",
    "t2runs": "197/4",
    "t2ovs": "19.2",
    "result": "RR won by 6 wickets",
    "winner": "RR",
    "rcb": false
  },
  {
    "id": 4,
    "date": "2026-03-31",
    "time": "19:30",
    "t1": "PBKS",
    "t2": "GT",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "t1runs": "201/6",
    "t1ovs": "20",
    "t2runs": "175/9",
    "t2ovs": "20",
    "result": "PBKS won by 26 runs",
    "winner": "PBKS",
    "rcb": false
  },
  {
    "id": 5,
    "date": "2026-04-01",
    "time": "19:30",
    "t1": "LSG",
    "t2": "DC",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "t1runs": "155/8",
    "t1ovs": "20",
    "t2runs": "159/4",
    "t2ovs": "18.4",
    "result": "DC won by 6 wickets",
    "winner": "DC",
    "rcb": false
  },
  {
    "id": 6,
    "date": "2026-04-02",
    "time": "19:30",
    "t1": "KKR",
    "t2": "SRH",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "t1runs": "179/7",
    "t1ovs": "20",
    "t2runs": "182/5",
    "t2ovs": "19.1",
    "result": "SRH won by 5 wickets",
    "winner": "SRH",
    "rcb": false
  },
  {
    "id": 7,
    "date": "2026-04-03",
    "time": "19:30",
    "t1": "CSK",
    "t2": "PBKS",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "t1runs": "188/6",
    "t1ovs": "20",
    "t2runs": "192/4",
    "t2ovs": "19.4",
    "result": "PBKS won by 6 wickets",
    "winner": "PBKS",
    "rcb": false
  },
  {
    "id": 8,
    "date": "2026-04-04",
    "time": "15:30",
    "t1": "DC",
    "t2": "MI",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "t1runs": "178/5",
    "t1ovs": "20",
    "t2runs": "165/9",
    "t2ovs": "20",
    "result": "DC won by 13 runs",
    "winner": "DC",
    "rcb": false
  },
  {
    "id": 9,
    "date": "2026-04-04",
    "time": "19:30",
    "t1": "GT",
    "t2": "RR",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "t1runs": "204/8",
    "t1ovs": "20",
    "t2runs": "210/6",
    "t2ovs": "20",
    "result": "RR won by 6 runs",
    "winner": "RR",
    "rcb": false
  },
  {
    "id": 11,
    "date": "2026-04-05",
    "time": "19:30",
    "t1": "RCB",
    "t2": "CSK",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "result": null,
    "rcb": true
  },
  {
    "id": 10,
    "date": "2026-04-05",
    "time": "15:30",
    "t1": "SRH",
    "t2": "LSG",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 12,
    "date": "2026-04-06",
    "time": "19:30",
    "t1": "KKR",
    "t2": "PBKS",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 13,
    "date": "2026-04-07",
    "time": "19:30",
    "t1": "RR",
    "t2": "MI",
    "venue": "Barsapara Cricket Stadium",
    "city": "Guwahati",
    "result": null,
    "rcb": false
  },
  {
    "id": 14,
    "date": "2026-04-08",
    "time": "19:30",
    "t1": "DC",
    "t2": "GT",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 15,
    "date": "2026-04-09",
    "time": "19:30",
    "t1": "KKR",
    "t2": "LSG",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 16,
    "date": "2026-04-10",
    "time": "19:30",
    "t1": "RR",
    "t2": "RCB",
    "venue": "Barsapara Cricket Stadium",
    "city": "Guwahati",
    "result": null,
    "rcb": true
  },
  {
    "id": 17,
    "date": "2026-04-11",
    "time": "19:30",
    "t1": "SRH",
    "t2": "CSK",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 18,
    "date": "2026-04-12",
    "time": "19:30",
    "t1": "MI",
    "t2": "RCB",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": true
  },
  {
    "id": 19,
    "date": "2026-04-13",
    "time": "15:30",
    "t1": "DC",
    "t2": "KKR",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 20,
    "date": "2026-04-13",
    "time": "19:30",
    "t1": "RR",
    "t2": "LSG",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 21,
    "date": "2026-04-15",
    "time": "19:30",
    "t1": "RCB",
    "t2": "LSG",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "result": null,
    "rcb": true
  },
  {
    "id": 22,
    "date": "2026-04-16",
    "time": "19:30",
    "t1": "CSK",
    "t2": "KKR",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "result": null,
    "rcb": false
  },
  {
    "id": 23,
    "date": "2026-04-17",
    "time": "19:30",
    "t1": "SRH",
    "t2": "PBKS",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 24,
    "date": "2026-04-18",
    "time": "15:30",
    "t1": "RCB",
    "t2": "DC",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "result": null,
    "rcb": true
  },
  {
    "id": 25,
    "date": "2026-04-18",
    "time": "19:30",
    "t1": "GT",
    "t2": "MI",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 26,
    "date": "2026-04-19",
    "time": "19:30",
    "t1": "RR",
    "t2": "CSK",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 27,
    "date": "2026-04-20",
    "time": "15:30",
    "t1": "SRH",
    "t2": "GT",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 28,
    "date": "2026-04-20",
    "time": "19:30",
    "t1": "PBKS",
    "t2": "KKR",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "result": null,
    "rcb": false
  },
  {
    "id": 29,
    "date": "2026-04-21",
    "time": "19:30",
    "t1": "DC",
    "t2": "LSG",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 30,
    "date": "2026-04-22",
    "time": "19:30",
    "t1": "MI",
    "t2": "RR",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 31,
    "date": "2026-04-23",
    "time": "19:30",
    "t1": "CSK",
    "t2": "GT",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "result": null,
    "rcb": false
  },
  {
    "id": 32,
    "date": "2026-04-24",
    "time": "19:30",
    "t1": "RCB",
    "t2": "GT",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "result": null,
    "rcb": true
  },
  {
    "id": 33,
    "date": "2026-04-25",
    "time": "15:30",
    "t1": "KKR",
    "t2": "RR",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 34,
    "date": "2026-04-25",
    "time": "19:30",
    "t1": "PBKS",
    "t2": "MI",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "result": null,
    "rcb": false
  },
  {
    "id": 35,
    "date": "2026-04-26",
    "time": "15:30",
    "t1": "LSG",
    "t2": "SRH",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "result": null,
    "rcb": false
  },
  {
    "id": 36,
    "date": "2026-04-26",
    "time": "19:30",
    "t1": "DC",
    "t2": "CSK",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 37,
    "date": "2026-04-27",
    "time": "15:30",
    "t1": "GT",
    "t2": "KKR",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 38,
    "date": "2026-04-27",
    "time": "19:30",
    "t1": "RR",
    "t2": "PBKS",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 39,
    "date": "2026-04-28",
    "time": "19:30",
    "t1": "MI",
    "t2": "DC",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 40,
    "date": "2026-04-29",
    "time": "19:30",
    "t1": "SRH",
    "t2": "RCB",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": true
  },
  {
    "id": 41,
    "date": "2026-04-30",
    "time": "19:30",
    "t1": "GT",
    "t2": "RCB",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": true
  },
  {
    "id": 42,
    "date": "2026-05-01",
    "time": "19:30",
    "t1": "LSG",
    "t2": "CSK",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "result": null,
    "rcb": false
  },
  {
    "id": 43,
    "date": "2026-05-02",
    "time": "15:30",
    "t1": "RR",
    "t2": "SRH",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 44,
    "date": "2026-05-02",
    "time": "19:30",
    "t1": "MI",
    "t2": "PBKS",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 45,
    "date": "2026-05-03",
    "time": "15:30",
    "t1": "KKR",
    "t2": "DC",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 46,
    "date": "2026-05-03",
    "time": "19:30",
    "t1": "CSK",
    "t2": "GT",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "result": null,
    "rcb": false
  },
  {
    "id": 47,
    "date": "2026-05-04",
    "time": "19:30",
    "t1": "SRH",
    "t2": "LSG",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 48,
    "date": "2026-05-05",
    "time": "19:30",
    "t1": "RR",
    "t2": "KKR",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 49,
    "date": "2026-05-06",
    "time": "19:30",
    "t1": "DC",
    "t2": "PBKS",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 50,
    "date": "2026-05-07",
    "time": "19:30",
    "t1": "GT",
    "t2": "MI",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 51,
    "date": "2026-05-08",
    "time": "19:30",
    "t1": "LSG",
    "t2": "RR",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "result": null,
    "rcb": false
  },
  {
    "id": 52,
    "date": "2026-05-09",
    "time": "15:30",
    "t1": "MI",
    "t2": "CSK",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 53,
    "date": "2026-05-09",
    "time": "19:30",
    "t1": "KKR",
    "t2": "SRH",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 54,
    "date": "2026-05-10",
    "time": "19:30",
    "t1": "RCB",
    "t2": "MI",
    "venue": "Shaheed Veer Narayan Singh Stadium",
    "city": "Raipur",
    "result": null,
    "rcb": true
  },
  {
    "id": 55,
    "date": "2026-05-11",
    "time": "15:30",
    "t1": "PBKS",
    "t2": "GT",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "result": null,
    "rcb": false
  },
  {
    "id": 56,
    "date": "2026-05-11",
    "time": "19:30",
    "t1": "DC",
    "t2": "RR",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 57,
    "date": "2026-05-12",
    "time": "19:30",
    "t1": "LSG",
    "t2": "KKR",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "result": null,
    "rcb": false
  },
  {
    "id": 58,
    "date": "2026-05-13",
    "time": "19:30",
    "t1": "CSK",
    "t2": "SRH",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "result": null,
    "rcb": false
  },
  {
    "id": 59,
    "date": "2026-05-14",
    "time": "19:30",
    "t1": "GT",
    "t2": "DC",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 60,
    "date": "2026-05-15",
    "time": "19:30",
    "t1": "PBKS",
    "t2": "RR",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "result": null,
    "rcb": false
  },
  {
    "id": 61,
    "date": "2026-05-16",
    "time": "15:30",
    "t1": "MI",
    "t2": "KKR",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 62,
    "date": "2026-05-16",
    "time": "19:30",
    "t1": "SRH",
    "t2": "GT",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 63,
    "date": "2026-05-17",
    "time": "15:30",
    "t1": "PBKS",
    "t2": "RCB",
    "venue": "HPCA Stadium",
    "city": "Dharamsala",
    "result": null,
    "rcb": true
  },
  {
    "id": 64,
    "date": "2026-05-17",
    "time": "19:30",
    "t1": "DC",
    "t2": "LSG",
    "venue": "Arun Jaitley Stadium",
    "city": "Delhi",
    "result": null,
    "rcb": false
  },
  {
    "id": 65,
    "date": "2026-05-18",
    "time": "15:30",
    "t1": "RR",
    "t2": "CSK",
    "venue": "Sawai Mansingh Stadium",
    "city": "Jaipur",
    "result": null,
    "rcb": false
  },
  {
    "id": 66,
    "date": "2026-05-18",
    "time": "19:30",
    "t1": "KKR",
    "t2": "MI",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  },
  {
    "id": 67,
    "date": "2026-05-19",
    "time": "19:30",
    "t1": "LSG",
    "t2": "SRH",
    "venue": "Ekana Cricket Stadium",
    "city": "Lucknow",
    "result": null,
    "rcb": false
  },
  {
    "id": 68,
    "date": "2026-05-20",
    "time": "15:30",
    "t1": "GT",
    "t2": "PBKS",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 69,
    "date": "2026-05-20",
    "time": "19:30",
    "t1": "CSK",
    "t2": "DC",
    "venue": "MA Chidambaram Stadium",
    "city": "Chennai",
    "result": null,
    "rcb": false
  },
  {
    "id": 70,
    "date": "2026-05-21",
    "time": "19:30",
    "t1": "MI",
    "t2": "RR",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 71,
    "date": "2026-05-22",
    "time": "15:30",
    "t1": "SRH",
    "t2": "KKR",
    "venue": "Rajiv Gandhi Intl. Stadium",
    "city": "Hyderabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 72,
    "date": "2026-05-22",
    "time": "19:30",
    "t1": "RCB",
    "t2": "LSG",
    "venue": "M. Chinnaswamy Stadium",
    "city": "Bengaluru",
    "result": null,
    "rcb": true
  },
  {
    "id": 73,
    "date": "2026-05-23",
    "time": "15:30",
    "t1": "PBKS",
    "t2": "DC",
    "venue": "PCA Stadium",
    "city": "Mullanpur",
    "result": null,
    "rcb": false
  },
  {
    "id": 74,
    "date": "2026-05-23",
    "time": "19:30",
    "t1": "GT",
    "t2": "RR",
    "venue": "Narendra Modi Stadium",
    "city": "Ahmedabad",
    "result": null,
    "rcb": false
  },
  {
    "id": 75,
    "date": "2026-05-24",
    "time": "15:30",
    "t1": "MI",
    "t2": "CSK",
    "venue": "Wankhede Stadium",
    "city": "Mumbai",
    "result": null,
    "rcb": false
  },
  {
    "id": 76,
    "date": "2026-05-24",
    "time": "19:30",
    "t1": "KKR",
    "t2": "LSG",
    "venue": "Eden Gardens",
    "city": "Kolkata",
    "result": null,
    "rcb": false
  }
];
